### ISSUE TITLE
Sentry transports not logging messages in CLI scripts if logged right before the script terminates

### ISSUE THREAD

**Issue by SteveKoontz** [synapsestudios/winston-sentry#30]
## Description
We need to add a `close` optional parameter that makes the Sentry SDK use the `close()` function when logging, which will make it promise to resolve all messages before continuing.

## ACs
- [ ] Add `close` boolean param to SentryTransport
- [ ] Add tests for close option
- [ ] Update version numbers and changelog

**Comment by spruce-bruce** [comment]
@SteveKoontz do you have the sentry sdk docs handy that you can link to?

**Comment by SteveKoontz** [comment]
> @SteveKoontz do you have the sentry sdk docs handy that you can link to?

https://getsentry.github.io/sentry-javascript/modules/node.html#close-1

**Comment by spruce-bruce** [comment]
Thanks! When I asked I didn't realize you were doing the work, I wanted a quick shortcut for whoever ended up grabbing this issue
